services:

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src/main/resources:/app/vol
    expose:
      - 8182
    ports:
      - 8182-8187:8182
    networks:
      - csvaggr
    deploy:
      mode: replicated
      replicas: 6
      update_config:
        parallelism: 6
        delay: 10s

networks:
  csvaggr:
    driver: bridge


