version: "3.9"

services:

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src/main/resources:/app/vol
    expose:
      - 8081
    ports:
      - 8081-8085:8081
    networks:
      - csvaggr
    deploy:
      replicas: 6
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure



networks:
  csvaggr:
    driver: bridge

  
