services:

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src/main/resources:/app/vol
    expose:
      - 8182
    ports:
      - 8182-8184:8182
    networks:
      - csvaggr
    deploy:
      mode: replicated
      replicas: 3

networks:
  csvaggr:
    driver: bridge


